<?php ob_start();?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

	<head>
	<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
	<title>File Uploaded</title>
	</head>
	
	<body>
		<?php
			//get the file name
			$name=$_FILES['upload']['name'];
			echo "File Name: $name<br/>";
			
			//get the file size
			$size=$_FILES['upload']['size'];
			echo "Size: $size<br/>";

			//get the type
			$type=$_FILES['upload']['type'];
			echo "Type: $type<br/>";

			//get the temporary location
			$tmp_name=$_FILES['upload']['tmp_name'];
			echo "Temp Name: $tmp_name<br/>";
			
			//create a unique name using the session id generated by the server
			session_start();
			$name=session_id().'-'.$name;
			
			//move to the "uploads" directory
			move_uploaded_file($tmp_name,"uploads/$name");
			
			//if the file is an image display the image
			if($type=="image/jpeg" || $type=="image/png")
			{
				echo '<img src="uploads/'.$name.'"/>';
			}
		?>
	</body>

</html>
<?php ob_flush();?> 